# 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기

SELECT  MONTH(START_DATE) AS MONTH , CAR_ID , COUNT(1) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN (SELECT CAR_ID 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE BETWEEN DATE_FORMAT('2022-08-01','%Y-%m-%d') AND DATE_FORMAT('2022-10-31','%Y-%m-%d') 
GROUP BY CAR_ID
HAVING COUNT(CAR_ID) >= 5 )
AND START_DATE BETWEEN DATE_FORMAT('2022-08-01','%Y-%m-%d') AND DATE_FORMAT('2022-10-31','%Y-%m-%d') 
GROUP BY  MONTH(START_DATE) , CAR_ID
ORDER BY MONTH(START_DATE) , CAR_ID DESC 


/* 
조건1 : CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블에서 대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차들에 대해서 해당 기간 동안의 월별 자동차 ID 별 총 대여 횟수(컬럼명: RECORDS) 리스트를 출력하는 SQL문을 작성

핵심 스킬1 : HAVING을 이용하여 대여 횟수가 5회 이상인 자동차 ID만 추출
핵심 스킬2 : WHERE IN 서브쿼리를 통해서 5회 이상인 자동차 ID의 월별 대여 횟수 추출 
*/
