# 오프라인/온라인 판매 데이터 통합하기

SELECT DATE_FORMAT(TOTAL.SALES_DATE, '%Y-%m-%d') as SALES_DATE , TOTAL.PRODUCT_ID , TOTAL.USER_ID , TOTAL.SALES_AMOUNT
FROM (
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
UNION ALL
SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID , SALES_AMOUNT
FROM OFFLINE_SALE
) TOTAL
WHERE DATE_FORMAT(TOTAL.SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY TOTAL.SALES_DATE , TOTAL.PRODUCT_ID , TOTAL.USER_ID


/* 
조건1 : ONLINE_SALE 테이블과 OFFLINE_SALE 테이블에서 2022년 3월의 오프라인/온라인 상품 판매 데이터의 판매 날짜, 상품ID, 유저ID, 판매량을 출력하는 SQL문을 작성

핵심 스킬1 : ONLINE_SALE 테이블과 OFFLINE_SALE 테이블을 UNION ALL 로 묶음  
핵심 스킬2 : DATE_FORMAT 함수를 이용해서 2022년 3월 데이터만 필터링  
( ORACLE :  TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') )

*/
