# ROOT 아이템 구하기 

SELECT DISTINCT I.ITEM_ID , I.ITEM_NAME
FROM ITEM_INFO I
INNER JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL 
ORDER BY I.ITEM_ID 

/* 
조건1 : ROOT 아이템을 찾아 아이템 ID(ITEM_ID), 아이템 명(ITEM_NAME)을 출력하는 SQL문

핵심 스킬1 : IS NULL 로 ROOT 아이템 추출 

*/
